service: name-service-serverless

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: target/nameservicelambda-2016.0.1.jar

functions:
  NameServiceGender:
    handler: org.johnripley.nameservicelambda.NameServiceGenderHandler::handleRequest
    events:
      - http:
          path: gender
          method: get
  NameServiceStats:
    handler: org.johnripley.nameservicelambda.NameServiceStatsHandler::handleRequest
    events:
      - http:
          path: stats
          method: get
